/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		CustomCalculator: typeof import('./components/CustomCalculator.vue')['default']
		CustomDialog: typeof import('./components/CustomDialog.vue')['default']
		CustomHeader: typeof import('./components/CustomHeader.vue')['default']
		DropArea: typeof import('./components/DropArea.vue')['default']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElOption: typeof import('element-plus/es')['ElOption']
		ElSelect: typeof import('element-plus/es')['ElSelect']
		ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
		ElTag: typeof import('element-plus/es')['ElTag']
		ElText: typeof import('element-plus/es')['ElText']
		NoFixedDialog: typeof import('./components/NoFixedDialog.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
	}
}
